version: '3'
services:
  mongodb:
    image: mongo:5.0.6
    ports:
      - "27017:27017"
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongosh --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: "--bind_ip_all"
volumes:
  pokemons-db:
